baseURL: https://agilebuckle.com
languageCode: en
title: 'AgileBuckle'
theme: ["PaperMod"]

languages:
  en:
    disabled: false
    languageCode: "en-us"
    languageDirection: ""
    languageName: ""
    title: ""
    weight: 0

params:
  profileMode:
    enabled: true
    title: "AgileBuckle"
    imageUrl: "/agilesanslogo.png"
    buttons:
      - name: Agile Sans
        url: "https://github.com/AgileBuckle/agile-sans"
      - name: Blog
        url: "https://blog.agilebuckle.com"

  socialIcons: # optional
    - name: "Github"
      url: "https://github.com/AgileBuckle"
    - name: "Email"
      url: "mailto:contact@agilebuckle.com"
    - name: "Mastodon"
      url: "https://wehavecookies.social/@agile"
    - name: "Pixelfed"
      url: "https://pixelfed.social/Agile"
    - name: "Sharkey"
      url: "https://federation.network/@agile"

  assets:
    disableFingerprinting: true
  customHead: true
