baseURL: https://agilebuckle.com
languageCode: en
title: "AgileBuckle"
theme: ["PaperMod"]

languages:
  en:
    disabled: false
    languageCode: ""
    languageDirection: ""
    languageName: ""
    title: ""
    weight: 0

params:
  profileMode:
    enabled: true
    title: AgileBuckle
    imageUrl: "/largelogo.png"

  socialIcons: # optional
    - name: "Github"
      url: "https://github.com/AgileBuckle"
    - name: "Blog"
      url: "https://pixelpress.substack.com"
    - name: "Email"
      url: "mailto:contact@agilebuckle.com"

